# Generated by Django 4.2.5 on 2024-06-29 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(db_index=True, default='', help_text='ID of the book', max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='book-ID')),
                ('image', models.TextField(default='', help_text='Image of the book', verbose_name='book-image')),
                ('hot', models.IntegerField(default=0, help_text='Hot of the book', verbose_name='book-hot')),
                ('title', models.CharField(default='', help_text='Title of the book', max_length=100, verbose_name='book-title')),
                ('description', models.TextField(default='', help_text='Description of the book', verbose_name='book-description')),
                ('raw_url', models.URLField(default='', help_text='Raw URL of the book', verbose_name='book-raw-url')),
                ('image_url', models.URLField(default='', help_text='Image URL of the book', verbose_name='book-image-url')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='episode-ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='episode-title')),
                ('raw_url', models.URLField(default='', verbose_name='episode-raw-url')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='apps.book')),
            ],
            options={
                'verbose_name': 'Episode',
                'verbose_name_plural': 'Episodes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='tag-name')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='image-ID')),
                ('index', models.IntegerField(default=0, verbose_name='image-index')),
                ('image', models.TextField(default='', verbose_name='image')),
                ('raw_url', models.URLField(default='', verbose_name='image-raw-url')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='apps.episode')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(related_name='books', to='apps.tag'),
        ),
    ]
