# Generated by Django 4.2.5 on 2024-06-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['index', 'id'], 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AddField(
            model_name='episode',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs', verbose_name='episode-pdf'),
        ),
    ]
