# Generated by Django 4.2.5 on 2024-06-30 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_image_options_episode_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['book__id', 'id', 'title'], 'verbose_name': 'Episode', 'verbose_name_plural': 'Episodes'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['episode__id', 'index', 'id'], 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
    ]
